# Generated by Django 5.2.2 on 2025-06-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категория кораллов',
                'verbose_name_plural': 'Категории кораллов',
            },
        ),
        migrations.CreateModel(
            name='CertificateStatuses',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Статус сертификата',
                'verbose_name_plural': 'Статусы сертификатов',
            },
        ),
        migrations.CreateModel(
            name='CertificateTypes',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Тип сертификата',
                'verbose_name_plural': 'Типы сертификатов',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderStatuses',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Seas',
            fields=[
                ('id_sea', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Море',
                'verbose_name_plural': 'Моря',
            },
        ),
        migrations.CreateModel(
            name='Corals',
            fields=[
                ('id_coral', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.PROTECT, to='store.categories')),
            ],
            options={
                'verbose_name': 'Коралл',
                'verbose_name_plural': 'Кораллы',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_coral', models.ForeignKey(db_column='id_coral', on_delete=django.db.models.deletion.PROTECT, to='store.corals')),
                ('id_order', models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.PROTECT, to='store.orders')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id_certificate', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('id_status', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.PROTECT, to='store.certificatestatuses')),
                ('id_type', models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.PROTECT, to='store.certificatetypes')),
                ('id_coral', models.ForeignKey(db_column='id_coral', on_delete=django.db.models.deletion.PROTECT, to='store.corals')),
                ('id_order', models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.PROTECT, to='store.orders')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='id_status',
            field=models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.PROTECT, to='store.orderstatuses'),
        ),
        migrations.CreateModel(
            name='Reefs',
            fields=[
                ('id_reef', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('coordinate', models.TextField(blank=True, null=True)),
                ('id_country', models.ForeignKey(db_column='id_country', on_delete=django.db.models.deletion.PROTECT, to='store.countries')),
                ('id_sea', models.ForeignKey(db_column='id_sea', on_delete=django.db.models.deletion.PROTECT, to='store.seas')),
            ],
            options={
                'verbose_name': 'Риф',
                'verbose_name_plural': 'Рифы',
            },
        ),
        migrations.AddField(
            model_name='corals',
            name='id_reef',
            field=models.ForeignKey(db_column='id_reef', on_delete=django.db.models.deletion.PROTECT, to='store.reefs'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('id_account', models.ForeignKey(db_column='id_account', on_delete=django.db.models.deletion.PROTECT, to='store.accounts')),
                ('id_role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.PROTECT, to='store.roles')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('id_coral', models.ForeignKey(db_column='id_coral', on_delete=django.db.models.deletion.PROTECT, to='store.corals')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, to='store.users')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, to='store.users'),
        ),
    ]
