# Generated by Django 5.2.7 on 2026-01-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id_airplane', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.IntegerField()),
                ('economy_capacity', models.IntegerField(blank=True, null=True)),
                ('business_capacity', models.IntegerField(blank=True, null=True)),
                ('first_capacity', models.IntegerField(blank=True, null=True)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('seats_row', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Самолет',
                'verbose_name_plural': 'Самолеты',
                'db_table': 'airplanes',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id_airport', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
                'db_table': 'airports',
            },
        ),
        migrations.CreateModel(
            name='BaggageType',
            fields=[
                ('id_baggage_type', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(choices=[('HAND', 'Ручная кладь'), ('STANDARD', 'Стандартный'), ('EXTRA', 'Дополнительный'), ('SPORT', 'Спортивный инвентарь'), ('OVERSIZE', 'Крупногабаритный')], max_length=50, unique=True)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Тип багажа',
                'verbose_name_plural': 'Типы багажа',
                'db_table': 'baggage_types',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id_class', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(choices=[('ECONOMY', 'Эконом'), ('BUSINESS', 'Бизнес'), ('FIRST', 'Первый')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id_passenger', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('birthday', models.DateField()),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
                'db_table': 'passengers',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(choices=[('CARD', 'Карта'), ('CASH', 'Наличные'), ('ONLINE', 'Онлайн')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('COMPLETED', 'Завершен'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id_audit', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('operation', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline.account')),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журналы аудита',
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id_flight', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Запланирован'), ('DELAYED', 'Задержан'), ('CANCELLED', 'Отменен'), ('COMPLETED', 'Выполнен')], default='SCHEDULED', max_length=30)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('airplane_id', models.ForeignKey(db_column='airplane_id', on_delete=django.db.models.deletion.CASCADE, to='airline.airplane')),
                ('arrival_airport_id', models.ForeignKey(db_column='arrival_airport_id', on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='airline.airport')),
                ('departure_airport_id', models.ForeignKey(db_column='departure_airport_id', on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='airline.airport')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'db_table': 'flights',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='airline.role'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('BOOKED', 'Забронирован'), ('PAID', 'Оплачен'), ('CHECKED_IN', 'Зарегистрирован'), ('CANCELLED', 'Отменен')], default='BOOKED', max_length=20)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='airline.class')),
                ('flight_id', models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, to='airline.flight')),
                ('passenger_id', models.ForeignKey(db_column='passenger_id', on_delete=django.db.models.deletion.CASCADE, to='airline.passenger')),
                ('payment_id', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline.payment')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id_baggage', models.AutoField(primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('baggage_tag', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Зарегистрирован'), ('LOADED', 'Загружен'), ('DELIVERED', 'Выдан'), ('LOST', 'Утерян')], default='REGISTERED', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('baggage_type_id', models.ForeignKey(db_column='baggage_type_id', on_delete=django.db.models.deletion.CASCADE, to='airline.baggagetype')),
                ('ticket_id', models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='baggage_items', to='airline.ticket')),
            ],
            options={
                'verbose_name': 'Багаж',
                'verbose_name_plural': 'Багаж',
                'db_table': 'baggage',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14)),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('birthday', models.DateField()),
                ('account_id', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='airline.account')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='airline.user'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(condition=models.Q(('departure_time__lt', models.F('arrival_time'))), name='check_departure_before_arrival'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('flight_id', 'seat_number'), name='unique_flight_seat'),
        ),
    ]
