# Generated by Django 5.2.7 on 2026-02-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passenger_id',
            field=models.ForeignKey(blank=True, db_column='passenger_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='airline.passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Свободен'), ('BOOKED', 'Забронирован'), ('PAID', 'Оплачен'), ('CHECKED_IN', 'Зарегистрирован'), ('CANCELLED', 'Отменен')], default='AVAILABLE', max_length=20),
        ),
    ]
