FROM python:3.10

# Установка рабочей директории
WORKDIR /app

# Копируем зависимости
COPY requirements.txt /app/

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем Bash-скрипт в контейнер
COPY entrypoint.sh /app/entrypoint.sh

# Делаем Bash-скрипт исполняемым
RUN chmod +x /app/entrypoint.sh

# Копирование проекта
COPY . /app/

# Инструкция для порта
EXPOSE 8000

# Команда для запуска приложения
CMD ["./entrypoint.sh"]

# docker cp "product_list2.html" "cf61f337b3be:/app/crudapp/templates/crudapp/product_list.html"