version: '3.8'

services:
  web:
    restart: always
    build: .
    volumes:
      - templates:/app/crudapp/templates/crudapp # volumes
      - .\crudapp\templates\crudapp\product_form.html:/app/crudapp/templates/crudapp/product_form.html # mount
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: always
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=myproject_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  templates:

    # docker-compose up
